const autoLanguage = 'auto';

const dictationLanguages = <String, String>{
  autoLanguage: 'Auto-detect',
  'en': 'English',
  'zh': '中文',
  'de': 'Deutsch',
  'es': 'Español',
  'ru': 'Русский',
  'ko': '한국어',
  'fr': 'Français',
  'ja': '日本語',
  'pt': 'Português',
  'tr': 'Türkçe',
  'pl': 'Polski',
  'ca': 'Català',
  'nl': 'Nederlands',
  'ar': 'العربية',
  'sv': 'Svenska',
  'it': 'Italiano',
  'id': 'Bahasa Indonesia',
  'hi': 'हिन्दी',
  'fi': 'Suomi',
  'vi': 'Tiếng Việt',
  'he': 'עברית',
  'uk': 'Українська',
  'el': 'Ελληνικά',
  'ms': 'Bahasa Melayu',
  'cs': 'Čeština',
  'ro': 'Română',
  'da': 'Dansk',
  'hu': 'Magyar',
  'ta': 'தமிழ்',
  'no': 'Norsk',
  'th': 'ไทย',
  'ur': 'اردو',
  'hr': 'Hrvatski',
  'bg': 'Български',
  'lt': 'Lietuvių',
  'la': 'Latina',
  'mi': 'Māori',
  'ml': 'മലയാളം',
  'cy': 'Cymraeg',
  'sk': 'Slovenčina',
  'te': 'తెలుగు',
  'fa': 'فارسی',
  'lv': 'Latviešu',
  'bn': 'বাংলা',
  'sr': 'Српски',
  'az': 'Azərbaycan',
  'sl': 'Slovenščina',
  'kn': 'ಕನ್ನಡ',
  'et': 'Eesti',
  'mk': 'Македонски',
  'br': 'Brezhoneg',
  'eu': 'Euskara',
  'is': 'Íslenska',
  'hy': 'Հայերեն',
  'ne': 'नेपाली',
  'mn': 'Монгол',
  'bs': 'Bosanski',
  'kk': 'Қазақша',
  'sq': 'Shqip',
  'sw': 'Kiswahili',
  'gl': 'Galego',
  'mr': 'मराठी',
  'pa': 'ਪੰਜਾਬੀ',
  'si': 'සිංහල',
  'km': 'ខ្មែរ',
  'sn': 'Shona',
  'yo': 'Yorùbá',
  'so': 'Soomaali',
  'af': 'Afrikaans',
  'oc': 'Occitan',
  'ka': 'ქართული',
  'be': 'Беларуская',
  'tg': 'Тоҷикӣ',
  'sd': 'سنڌي',
  'gu': 'ગુજરાતી',
  'am': 'አማርኛ',
  'yi': 'ייִדיש',
  'lo': 'ລາວ',
  'uz': "Oʻzbek",
  'fo': 'Føroyskt',
  'ht': 'Kreyòl Ayisyen',
  'ps': 'پښتو',
  'tk': 'Türkmen',
  'nn': 'Nynorsk',
  'mt': 'Malti',
  'sa': 'संस्कृतम्',
  'lb': 'Lëtzebuergesch',
  'my': 'မြန်မာ',
  'bo': 'བོད་སྐད་',
  'tl': 'Tagalog',
  'mg': 'Malagasy',
  'as': 'অসমীয়া',
  'tt': 'Татар',
  'haw': 'ʻŌlelo Hawaiʻi',
  'ln': 'Lingála',
  'ha': 'Hausa',
  'ba': 'Башҡорт',
  'jw': 'Basa Jawa',
  'su': 'Basa Sunda',
  'yue': '粵語',
  'zh-TW': '中文 (台灣)',
  'zh-HK': '中文 (香港)',
  'zh-CN': '中文 (简体)',
  'pt-PT': 'Português (Portugal)',
  'pt-BR': 'Português (Brasil)',
};

const orderedDictationLanguageCodes = <String>[
  'en',
  'es',
  'de',
  'zh',
  'zh-TW',
  'zh-HK',
  'zh-CN',
  'ru',
  'ko',
  'fr',
  'ja',
  'pt',
  'pt-PT',
  'pt-BR',
  'tr',
  'pl',
  'ca',
  'nl',
  'ar',
  'sv',
  'it',
  'id',
  'hi',
  'fi',
  'vi',
  'he',
  'uk',
  'el',
  'ms',
  'cs',
  'ro',
  'da',
  'hu',
  'ta',
  'no',
  'th',
  'ur',
  'hr',
  'bg',
  'lt',
  'la',
  'mi',
  'ml',
  'cy',
  'sk',
  'te',
  'fa',
  'lv',
  'bn',
  'sr',
  'az',
  'sl',
  'kn',
  'et',
  'mk',
  'br',
  'eu',
  'is',
  'hy',
  'ne',
  'mn',
  'bs',
  'kk',
  'sq',
  'sw',
  'gl',
  'mr',
  'pa',
  'si',
  'km',
  'sn',
  'yo',
  'so',
  'af',
  'oc',
  'ka',
  'be',
  'tg',
  'sd',
  'gu',
  'am',
  'yi',
  'lo',
  'uz',
  'fo',
  'ht',
  'ps',
  'tk',
  'nn',
  'mt',
  'sa',
  'lb',
  'my',
  'bo',
  'tl',
  'mg',
  'as',
  'tt',
  'haw',
  'ln',
  'ha',
  'ba',
  'jw',
  'su',
  'yue',
];

String getDisplayNameForLanguage(String code) {
  return dictationLanguages[code] ?? code;
}

String getLanguageChipLabel(String code) {
  return code.split('-').first.toUpperCase();
}
